[tool.black]
line-length = 100
target-version = ["py311"]
include = '\.pyi?$'

[tool.ruff]
line-length = 100
target-version = "py311"
exclude = ["dist", "build", ".venv"]

[tool.ruff.lint]
select = ["E", "F", "I"]
fixable = ["ALL"]
